### ISSUE TITLE
Generating and link reference rustdoc from darwinia code

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#1]
Example:

https://substrate.dev/rustdocs/master/sc_service/index.html

Note:

Might need help from core developers @yanganto @clearloop

**Comment by AlexChien** [comment]
Updated by commit 35646aa7156ce8b8e95dc98d849b7ce19f07f950 and 3dd6459f5983001810f30dea0e73bd8992059278.

https://docs.darwinia.network/rustdocs/

Links will be added laterr.
