### ISSUE TITLE
Use Crowdin for translations

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#107]
docusaurus supports crowdin well.

https://docusaurus.io/docs/en/translation#crowdin

**Comment by AlexChien** [comment]
I am not a Crowdin fan personally. They smash contents into sentence strings, better for interface translations.  But for large chunk of content that is context sensitive or with rich format, it seems to be troublesome.

**Comment by wuminzhe** [comment]
@AlexChien Yes, that is a problem. 
I see other projects in use, and crowdin can be configured to combine automatic translation and manual translation.
Give up if it's inconvenient.
