### ISSUE TITLE
Uniform terminology

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#129]
- [x] RING 全部大写
- [x] KTON 全部大写
- [x] Crab RING: `CRING`, `CRINGs`
- [x] Crab KTON: `CKTON`, `CKTONs`
- [x] Subscan: `Subscan`
- [x] Darwinia Network 首字大写
- [x] Darwinia Crab Network 或者 Crab Network

**Comment by hackfisher** [comment]
> Darwinia Crab Network

Full Name: Darwinia Crab Network (Alias: Crab Network)
Short Name: Crab

**Comment by hackfisher** [comment]
> Crab RING: `CRING`, `CRINGs`

Stale: Refer https://github.com/darwinia-network/darwinia/issues/746

**Comment by hackfisher** [comment]
Related https://itering.notion.site/Glossary-4d4c11bb1fb14a6c8e5ccc87209cfaa3

Might need a terminology or glossary page for reference.

This issue is stale, closing it.
