### ISSUE TITLE
Workshop Index

### ISSUE THREAD

**Issue by AlexChien** [darwinia-network/darwinia-docs-deprecated#13]
Introduction about ChainReactions

- [x] [Chinese Overview](../blob/master/content/zh-CN/dev-workshop-index.md)
- [x] [English Overview](../blob/master/content/en/dev-workshop-index.md)

**Comment by tonytongxue** [comment]
cn done

**Comment by AlexChien** [comment]
Please update English as well, it's due for quite a while.

**Comment by tonytongxue** [comment]
done
