### ISSUE TITLE
Refactor content tree and structure.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#131]
Should split into different views for:

- General Users (Polkadot Apps{tokens, governance, staking etc.}, Bridge/Wormhole, Apps)
- Application(Smart contract) Developers (EVM & smart contract specificly)
- Protocol Developers (Protocol, RFC, Substrate)
- Validators and Bridgers.

**Comment by wuminzhe** [comment]
1. Make the directory structure consistent with the doc tree
`technology/overview` in `website/sidebars.json`  ->  `content/en/technology/overview.md`

2. Missing docs
wallet(apps) introduction

**Comment by hackfisher** [comment]
I agree with the latest changes for the structure.

Followup suggestion:
1. Submit the code changes to a branch, and create a pull request for easier review and comment.
2. Move the staging test link from `http://192.168.200.82:3000/docs/en/new/technology/overview` to https://docs.darwinia.network.l2me.com, @wi1dcard, would you help on this? 
3. Release process enhancement? Using master branch as staging env, and release by tagging new release.

**Comment by wi1dcard** [comment]
Sure yes, I'll check it out and submit a PR to update the deployment flow.
