### ISSUE TITLE
Versions update in docs

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#140]

**Comment by wi1dcard** [comment]
What do you mean "versions update"?

**Comment by wuminzhe** [comment]
@wi1dcard I mean the Darwinia version should be updated. Another way is to use a pattern instead of a specific version number.

**Comment by wi1dcard** [comment]
Has this issue been resolved?

**Comment by wuminzhe** [comment]
yes
