### ISSUE TITLE
Is "Account" "账户" or "账号" in Chinese?

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#142]

**Comment by wi1dcard** [comment]
我认为需要视情况而定，“账户” 听起来更像是一本存储你资金来往的账本，能够体现经济要素变动；“账号” 则更有 “一对 Username 和 Password 组合” 的意味。

**Comment by wuminzhe** [comment]
apps里面现在用的是账号

**Comment by wuminzhe** [comment]
https://github.com/darwinia-network/apps/issues/186
