### ISSUE TITLE
wiki-us-governance is empty

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#150]

**Comment by acgxv** [comment]
https://wiki.polkadot.network/docs/en/learn-governance#docsNav

**Comment by acgxv** [comment]
All the things are the same. Do we really need this?

**Comment by wuminzhe** [comment]
@AlexChien @HackFisher

**Comment by hackfisher** [comment]
Same convention.

Give entry, an introduction and an additional link to substrate/polkadot details docs.

**Comment by 1022ranji** [comment]
wiki-us-governance is completed.
https://docs.darwinia.network/understand-darwinia/wiki-us-governance
