### ISSUE TITLE
wiki-us-txfee is empty

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#151]
Transaction Fees

**Comment by acgxv** [comment]
https://wiki.polkadot.network/docs/en/learn-transaction-fees#docsNav

**Comment by wuminzhe** [comment]
@HackFisher Whether this chapter should be kept or deleted?

**Comment by hackfisher** [comment]
We could give a general description and attach a link to polkadot wiki who are interested in details.
