### ISSUE TITLE
Pangolin RPC endpoints is outdated

### ISSUE THREAD

**Issue by wi1dcard** [darwinia-network/darwinia-docs-deprecated#165]
For example: https://github.com/darwinia-network/docs/blob/master/content/en/dev-tut-dvm-deposit.md

Please update it to `wss://pangolin-rpc.darwinia.network`.

**Comment by wuminzhe** [comment]
http://t1.hkg.itering.com:9933 -> https://pangolin-rpc.darwinia.network ?

**Comment by wuminzhe** [comment]
Fixed
