### ISSUE TITLE
Add docs for ERC20 registration protocol

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#170]
Refer companion PRs:

https://github.com/darwinia-network/darwinia-common/pull/656

https://github.com/darwinia-network/darwinia-bridge-sol/pull/32

[转接桥注册协议（ERC20）.pdf](https://github.com/darwinia-network/docs/files/6669344/ERC20.pdf)

Need more general protocol description document from @xiaoch05

**Comment by wuminzhe** [comment]
https://www.notion.so/itering/eb89924ef42c487c8c5f8a92537ef0a1

**Comment by 1022ranji** [comment]
turn to #231
