### ISSUE TITLE
Add docs: BSC finality light client and pallet

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#171]
References: Substrate grandpa and header relay's finality loop
https://github.com/paritytech/parity-bridges-common/blob/master/modules/grandpa/src/lib.rs

https://github.com/paritytech/parity-bridges-common/blob/master/relays/finality/src/lib.rs

This might be easier if develop based on parity-bridges-common by adding a new network support and a new consensus (Clique for Rinky, BSC, Heco) 

https://github.com/darwinia-network/parity-bridges-common

**Comment by hackfisher** [comment]
Related pull request: https://github.com/darwinia-network/darwinia-common/pull/646

More Ref:

https://docs.binance.org/smart-chain/guides/concepts/consensus.html#security-and-finality

**Comment by wuminzhe** [comment]
https://www.notion.so/itering/BSC-Finality-Light-Client-322457dc636d467891ad04aa3156610e

**Comment by 1022ranji** [comment]
This doc has already been completed and it will be placed on the official website document at the end of October. more details: #231 
https://www.notion.so/itering/BSC-Finality-Light-Client-322457dc636d467891ad04aa3156610e
