### ISSUE TITLE
Update: Interoperate design between substrate and dvm

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#176]
1. If smart contracts want to call some substrate dispatch call, it should use Dispatch Precompile. Some refactor is required in mapping token factory implementations @xiaoch05 The can help remove the `Issuing` Precompile.

2. For the dispatch call scale encode required by smart contract before call Dispatch Precompile, there are no currently solidity SCALE library, another useful approach is to use a similar way by providing an Util Precompile to help encode dispatch calls. @AsceticBear @xiaoch05 

3. The reserved Precompile addresses are limited resources, so we should encourage to group similar functions into Precompiles as actions.  For example, we should merge `Withdraw` and `KTON` into one Precompile( `Currency`?), and for the new added  dispatch call encoding function, it should be only partial actions of Utils Precompile, and Utils Precompile can be extended to support more functions in future. @AsceticBear 

4. Security concerns related to infinite loop between smart contracts and dispatch call, with Dispatch Precompile, any ethereum address, including smart contract will be able to call any dispatch call as soon as it support normal `Origin`. So if some dispatch call support to pass in a callback in form of calling a user contract's method, then some attacker can build such a contract by call this dispatch call with a callback back to the contract's method it self, and causing infinite loop.

Need to test whether such an infinite loop is really a problem for us. @AsceticBear 

So we should add a security practice that we should not add user contract's method as callback of a dispatch call, or We must be very carefully to audit it for the reasons mentioned above. (H. in https://github.com/darwinia-network/darwinia/wiki/Best-Practice-for-Darwinia-Security-Review)

**Comment by boundless-forest** [comment]
I look over the points listed above, I think we can close this issue now. @HackFisher @xiaoch05
