### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia-docs-deprecated#184]
https://darwinia.network/economic_model

![image](https://user-images.githubusercontent.com/11801722/128680508-75ba05ab-a4c2-47d5-9078-b551cc984d8e.png)

Click `How to Stake` and jump to 404.

**Comment by AsceticBear** [comment]
https://darwinia.network/community

![image](https://user-images.githubusercontent.com/11801722/128681998-5174f38a-5deb-4cc9-b2df-967358223b6f.png)

Another 404 link

**Comment by boundless-forest** [comment]
![image](https://user-images.githubusercontent.com/11801722/130540193-013aa014-4233-44f9-b880-f7813915e941.png)

404 link.
