### ISSUE TITLE
Add and syncing terminology and glossary page

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#223]
Could be syncing from https://itering.notion.site/Glossary-4d4c11bb1fb14a6c8e5ccc87209cfaa3 ?

And how to effectively maintain this?

This is open for long term syncing around topics related to glossary and terminology.

**Comment by 1022ranji** [comment]
Yes, it can be syncing from https://itering.notion.site/Glossary-4d4c11bb1fb14a6c8e5ccc87209cfaa3 
The document of glossary and terminology will be finished at the end of October, and the related task was assigned in issue #231
