### ISSUE TITLE
文档搜索功能

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/darwinia-docs-deprecated#234]
无法搜索
![image](https://user-images.githubusercontent.com/80877629/136641610-a9670987-4f92-4e78-a3fa-e58b730324b7.png)

**Comment by JayJay1024** [comment]
![image](https://user-images.githubusercontent.com/21007682/136739821-16db8350-2424-47c2-b010-a5eb05c4e269.png)

**Comment by acgxv** [comment]
A month passed. I can't see any improvement.

**Comment by 1022ranji** [comment]
Recently, PLO has a higher priority, and there are still some unfinished parts of the second phase of PLO. After it is completed, it will be arranged to deal with this issue.
