### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia-docs-deprecated#239]
https://darwinia.network/

![image](https://user-images.githubusercontent.com/11801722/137421614-334323de-8dc2-40d1-9f54-80894a426365.png)

![image](https://user-images.githubusercontent.com/11801722/137421640-7cb6c1b0-33be-4fab-872a-593c51580e15.png)

**Comment by 1022ranji** [comment]
It has been fixed.
