### ISSUE TITLE
Question About the Color of PNG's Transparent Background

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/darwinia-docs-deprecated#247]
![image](https://user-images.githubusercontent.com/16152305/140910248-28bd3b1c-0f0d-4266-8d69-2be9f139480f.png)

Would this be black better in dark mode?

**Comment by acgxv** [comment]
![image](https://user-images.githubusercontent.com/16152305/140912241-e531ad98-3794-415b-ac32-dce85170b594.png)
