### ISSUE TITLE
Inappropriate use of punctuation

### ISSUE THREAD

**Issue by dioweb3** [darwinia-network/darwinia-docs-deprecated#275]
https://docs.darwinia.network/understand-darwinia/wiki-us-tokens
![image](https://user-images.githubusercontent.com/45236466/162863957-3136197c-18d1-4103-8c13-12a417ef00ca.png)
Why is question mark

**Comment by ECJ222** [comment]
> https://docs.darwinia.network/understand-darwinia/wiki-us-tokens ![image](https://user-images.githubusercontent.com/45236466/162863957-3136197c-18d1-4103-8c13-12a417ef00ca.png) Why is question mark

It seems the page has been removed. @gravitiny

**Comment by wuminzhe** [comment]
yes, this is an outdated doc.
