### ISSUE TITLE
Add Toolbox's rpc method to generate session key

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#39]
~~https://docs.darwinia.network/docs/en/crab-tut-node#generate-session-key~~

Can use apps -> Toolbox -> Rpc ->author -> rotateKeys

This is easier way to operate.

**Comment by acgxv** [comment]
~~I'm working on 'how to boot a node'.~~

This should be a part of 'become a validator', not 'run a node'.

https://docs.darwinia.network/docs/en/crab-tut-validator#generate-session-key
