### ISSUE TITLE
Complete contributing guide and mastering markdown link

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#64]
https://wiki.polkadot.network/docs/en/contributing  Polkadot Wiki的这个Contributing Guide也可以参考和修改一下，加到我们的doc里面

https://guides.github.com/features/mastering-markdown/

**Comment by AlexChien** [comment]
这里有的

https://github.com/darwinia-network/docs/blob/master/content/en/wiki-contribute.md
