### ISSUE TITLE
Generate Session Keys in Rc2

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/darwinia-docs-deprecated#65]

**Comment by hackfisher** [comment]
@AurevoirXavier Could you give more decription?

**Comment by acgxv** [comment]
Something was outdated at that time.

I'm not sure if this issue was fixed.

Since RC2 we need to specify `--rpc-method unsafe` to enable the `author_rotateKeys`.

**Comment by hackfisher** [comment]
https://docs.darwinia.network/docs/zh-CN/wiki-tut-validator#%E8%BF%90%E8%A1%8C%E9%AA%8C%E8%AF%81%E4%BA%BA%E8%8A%82%E7%82%B9
