### ISSUE TITLE
author_rotateKeys need to use --rpc-methods Unsafe

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-docs-deprecated#71]
https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot#option-2-cli

**Comment by hackfisher** [comment]
@AurevoirXavier says that https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot#option-2-cli if for rc5

**Comment by freehere107** [comment]
https://github.com/darwinia-network/docs/commit/97248168b673774d096f1aabeb47750210b47e85
