### ISSUE TITLE
Top column description optimization discussion

### ISSUE THREAD

**Issue by yakio** [darwinia-network/darwinia-docs-deprecated#74]
主网相关内容是否继续叫wiki？还是改成Darwinia Mainnet好一点
![image](https://user-images.githubusercontent.com/46353690/93759390-ab46c280-fc3c-11ea-8c83-d8cd0349ce96.png)

**Comment by acgxv** [comment]
https://wiki.polkadot.network/

**Comment by nblogist** [comment]
@AurevoirXavier Do we need to change it?

**Comment by acgxv** [comment]
> @AurevoirXavier Do we need to change it?

I think we should update this. Follow polkadot's style.

**Comment by hackfisher** [comment]
stale
